// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Arrow: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/Arrow.vue')['default']
    AutoFitText: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/AutoFitText.vue')['default']
    CodeHighlightController: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/CodeHighlightController.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Hidden: typeof import('./theme/components/Hidden.vue')['default']
    LayoutFooter: typeof import('./theme/components/LayoutFooter.vue')['default']
    Mermaid: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/Mermaid.vue')['default']
    Monaco: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/Monaco.vue')['default']
    PlantUml: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/PlantUml.vue')['default']
    SlideCurrentNo: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/SlideCurrentNo.vue')['default']
    SlidesTotal: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/SlidesTotal.vue')['default']
    Transform: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/Transform.vue')['default']
    Tweet: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/Tweet.vue')['default']
    VAfter: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/VAfter.ts')['default']
    VClick: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/VClick.ts')['default']
    VClicks: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/VClicks.ts')['default']
    Youtube: typeof import('./../../../node_modules/.pnpm/@slidev+client@0.27.20_vite@2.9.15/node_modules/@slidev/client/builtin/Youtube.vue')['default']
  }
}

export { }
